include_recipe 'gentoo-support::portage_defaults'

package 'media-fonts/arphicfonts'
package 'media-fonts/droid'
package 'media-fonts/ipamonafont'
package 'media-fonts/noto'
package 'media-fonts/ja-ipafonts'
package 'media-fonts/takao-fonts'
package 'media-fonts/wqy-microhei'
package 'media-fonts/wqy-zenhei'
